public class HelloWorld {
    public static void displayHelloWorld() {
        System.debug('Hello Wednesday, great2222 world4444 !');
                System.debug('Hello Wednesday, great2222 world4444 !');

                System.debug('Hello Wednesday, great2222 world Version 2!');
                        System.debug('Hello Wednesday, great2222 world Version 2!');

                        System.debug('Hello Wednesday, great2222 world Version 2!');

                        System.debug('Hello Wednesday, great2222 world Version 2!');
		
        Integer a = 8;

    }
}